# Generated by Django 5.2.5 on 2025-08-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='concurrent_jobs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='failed_requests',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_request_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='requests_per_day',
        ),
        migrations.RemoveField(
            model_name='user',
            name='requests_per_hour',
        ),
        migrations.RemoveField(
            model_name='user',
            name='successful_requests',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_requests',
        ),
    ]
