# Generated by Django 5.2.5 on 2025-08-19 10:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('single_scrape', 'Single Scrape'), ('batch_scrape', 'Batch Scrape')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('tool_type', models.CharField(choices=[('google', 'Google'), ('chatgpt', 'ChatGPT'), ('perplexity', 'Perplexity')], db_index=True, max_length=20)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('progress', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_items', models.PositiveIntegerField(default=1)),
                ('processed_items', models.PositiveIntegerField(default=0)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('priority', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_duration', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='scraper_job_created_150cd8_idx'), models.Index(fields=['status', '-created_at'], name='scraper_job_status_2b2d62_idx'), models.Index(fields=['user_id', '-created_at'], name='scraper_job_user_id_805acc_idx'), models.Index(fields=['type', 'status'], name='scraper_job_type_1077f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(choices=[('scrapingBrowser', 'Scraping Browser'), ('residentialProxy', 'Residential Proxy')], max_length=50)),
                ('data', models.JSONField(blank=True, null=True)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('quality_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('quality_factors', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_results', to='scraper.job')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['keyword', '-created_at'], name='scraper_res_keyword_d639eb_idx'), models.Index(fields=['job'], name='scraper_res_job_id_c88b2c_idx'), models.Index(fields=['-quality_score'], name='scraper_res_quality_9aaaf3_idx'), models.Index(fields=['method', '-created_at'], name='scraper_res_method_a5f492_idx')],
            },
        ),
    ]
